from __future__ import annotations

import argparse
import ipaddress
import re
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from ad_ops_common import (  # noqa: E402
    DEFAULT_BUNDLE_NAME,
    require_workdir,
    short_summary,
    update_artifacts,
    write_json,
)


NODE_RE = re.compile(r"^(?P<host>[^:]+):(?P<port>[0-9]{1,5})$")
SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_.-]+")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a deterministic create bundle for an HTTP virtual service with X-Forwarded-For insertion.",
    )
    parser.add_argument("--vs-name", required=True, help="Virtual service name.")
    parser.add_argument("--vip", required=True, help="Virtual service VIP address.")
    parser.add_argument("--vport", required=True, help="Virtual service port, for example 80 or 8080.")
    parser.add_argument("--pool", required=True, help="Pool name.")
    parser.add_argument(
        "--node",
        action="append",
        required=True,
        help="Backend node as address:port. Repeat for multiple nodes.",
    )
    parser.add_argument("--http-profile", required=True, help="HTTP profile name for XFF insertion.")
    parser.add_argument("--header", default="X-Forwarded-For", help="HTTP header name. Default: X-Forwarded-For.")
    parser.add_argument("--description", default="Generated by ad-config-ops fixed VS+XFF workflow.")
    parser.add_argument("--out", type=Path, help=f"Bundle path. Defaults to workdir/{DEFAULT_BUNDLE_NAME}.")
    parser.add_argument(
        "--workdir",
        type=Path,
        help="Artifact work directory. Defaults to AD_OPS_WORKDIR, then ./ad_ops_workdir.",
    )
    return parser.parse_args(argv)


def validate_name(label: str, value: str) -> str:
    if not value.strip():
        raise ValueError(f"{label} is required")
    if len(value) > 63:
        raise ValueError(f"{label} must be <= 63 characters")
    return value.strip()


def validate_port(label: str, value: Any) -> int:
    try:
        port = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{label} must be an integer") from exc
    if port < 0 or port > 65535:
        raise ValueError(f"{label} must be between 0 and 65535")
    return port


def validate_header(value: str) -> str:
    header = value.strip()
    if not header:
        raise ValueError("--header is required")
    if len(header) > 63:
        raise ValueError("--header must be <= 63 characters")
    return header


def node_name(host: str, port: int, index: int) -> str:
    base = SAFE_NAME_RE.sub("_", f"node_{index}_{host}_{port}").strip("_")
    return base[:63] or f"node_{index}"


def parse_node(value: str, index: int) -> dict[str, Any]:
    match = NODE_RE.match(value.strip())
    if not match:
        raise ValueError(f"--node must use address:port, got: {value}")
    host = match.group("host")
    port = validate_port("--node port", match.group("port"))
    try:
        ipaddress.ip_address(host)
    except ValueError as exc:
        raise ValueError(f"--node host must be an IP address, got: {host}") from exc
    return {
        "name": node_name(host, port, index),
        "type": "ADDRESS",
        "address": host,
        "port": port,
        "state": "ENABLE",
        "weight": 10,
        "priority_level": 1,
    }


def validate_vip(value: str) -> str:
    vip = value.strip()
    try:
        ipaddress.ip_address(vip)
    except ValueError as exc:
        raise ValueError(f"--vip must be an IP address, got: {vip}") from exc
    return vip


def build_bundle(args: argparse.Namespace) -> dict[str, Any]:
    vs_name = validate_name("--vs-name", args.vs_name)
    pool = validate_name("--pool", args.pool)
    http_profile = validate_name("--http-profile", args.http_profile)
    header = validate_header(args.header)
    vip = validate_vip(args.vip)
    vport = str(validate_port("--vport", args.vport))
    nodes = [parse_node(value, index) for index, value in enumerate(args.node, start=1)]

    return {
        "version": 1,
        "generator": "render_vs_xff_bundle.py",
        "operations": [
            {
                "id": "create-http-profile-xff",
                "action": "create",
                "schema": "config.http_profile",
                "document": "slb/http-profile.js",
                "payload": {
                    "name": http_profile,
                    "description": args.description,
                    "source_address": {
                        "operation": "REQUEST-HEADER-INSERT-SRCIP",
                        "request_header": header,
                    },
                },
            },
            {
                "id": "create-pool-with-nodes",
                "action": "create",
                "schema": "config.pool",
                "document": "slb/pool.js",
                "payload": {
                    "name": pool,
                    "description": args.description,
                    "method": "ROUND-ROBIN",
                    "nodes": nodes,
                },
            },
            {
                "id": "create-virtual-service",
                "action": "create",
                "schema": "config.virtual_service",
                "document": "slb/virtual-service.js",
                "payload": {
                    "name": vs_name,
                    "description": args.description,
                    "state": "ENABLE",
                    "service": "HTTP",
                    "vips": [vip],
                    "vports": [vport],
                    "pool": pool,
                    "http_profile": http_profile,
                },
            },
        ],
    }


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        workdir = require_workdir(args.workdir)
        out = args.out or workdir / DEFAULT_BUNDLE_NAME
        bundle = build_bundle(args)
        write_json(out, bundle)
        artifacts = update_artifacts(workdir, bundle=out)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 2

    print(
        short_summary(
            ok=True,
            bundle=str(out),
            artifacts=str(artifacts),
            operation_count=len(bundle["operations"]),
            workflow="vs-xff-create",
            next_command=(
                "python3 skills/ad-config-ops/scripts/ad_ops_flow.py plan-and-render "
                f"--skill-root skills/ad-config-ops --bundle {out} --workdir {workdir}"
            ),
        ),
        end="",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
