from __future__ import annotations

import argparse
import ipaddress
import re
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from ad_ops_common import (  # noqa: E402
    DEFAULT_BUNDLE_NAME,
    remove_generated_artifacts,
    require_workdir,
    short_summary,
    update_artifacts,
    write_json,
)


NODE_RE = re.compile(r"^(?P<host>[^:]+):(?P<port>[0-9]{1,5})$")
SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_.-]+")
SERVICE_TYPES = {
    "IP",
    "ANY",
    "TCP-FORWARD",
    "TCP-PROXY",
    "UDP-FORWARD",
    "UDP-PROXY",
    "HTTP",
    "SSL-OFFLOAD",
    "SSL-OFFLOAD-HTTPS",
    "RADIUS",
    "DNS",
    "FTP",
    "SIP-TCP",
    "SIP-UDP",
    "8583",
}
PRE_RULE_ACTIONS = {
    "SCHED-POOL",
    "SCHED-POOL-AND-REWRITE",
    "TCP-FIN",
    "TCP-RST",
    "HTTP-RESPONSE",
    "URL-REDIRECT",
}
URI_MATCH_MODES = {
    "NONE",
    "EQUAL",
    "NON-EQUAL",
    "CONTAIN",
    "NON-CONTAIN",
    "WILDCARD",
    "NON-WILDCARD",
    "REGULAR",
    "NON-REGULAR",
}


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a deterministic SLB create bundle for a virtual service plus optional referenced resources.",
    )
    parser.add_argument("--vs-name", required=True, help="Virtual service name.")
    parser.add_argument("--service", default="HTTP", help="Virtual service type. Default: HTTP.")
    parser.add_argument("--vip", action="append", required=True, help="Virtual service VIP. Repeat for multiple VIPs.")
    parser.add_argument("--vport", action="append", required=True, help="Virtual service port. Repeat for multiple ports.")
    parser.add_argument("--pool", required=True, help="Pool name to reference from the virtual service.")
    parser.add_argument(
        "--node",
        action="append",
        default=[],
        help="Backend node as address:port. Repeat to create/update a pool with nodes.",
    )
    parser.add_argument("--create-pool", action="store_true", help="Create the referenced pool even when no nodes are provided.")
    profile_group = parser.add_mutually_exclusive_group()
    profile_group.add_argument("--http-profile", help="Reference an existing HTTP profile from the virtual service.")
    profile_group.add_argument("--create-http-profile-xff", help="Create and reference an HTTP profile that inserts XFF.")
    parser.add_argument("--xff-header", default="X-Forwarded-For", help="XFF header name for --create-http-profile-xff.")
    parser.add_argument("--pre-rule", action="append", default=[], help="Reference an existing pre-rule from the virtual service.")
    parser.add_argument("--create-pre-rule-http", help="Create and reference an HTTP pre-rule.")
    parser.add_argument("--pre-rule-action", default="SCHED-POOL", help="HTTP pre-rule action. Default: SCHED-POOL.")
    parser.add_argument("--pre-rule-sched-pool", help="Pool used by SCHED-POOL pre-rule actions. Defaults to --pool.")
    parser.add_argument("--pre-rule-uri-pattern", help="Optional URI pattern for the generated HTTP pre-rule.")
    parser.add_argument("--pre-rule-uri-mode", default="EQUAL", help="URI match mode when --pre-rule-uri-pattern is set.")
    parser.add_argument("--pre-rule-case-sensitive", choices=["ENABLE", "DISABLE"], default="DISABLE")
    parser.add_argument("--description", default="Generated by ad-config-ops SLB bundle workflow.")
    parser.add_argument("--out", type=Path, help=f"Bundle path. Defaults to workdir/{DEFAULT_BUNDLE_NAME}.")
    parser.add_argument(
        "--workdir",
        type=Path,
        help="Artifact work directory. Defaults to AD_OPS_WORKDIR, then ./ad_ops_workdir.",
    )
    return parser.parse_args(argv)


def normalize_choice(label: str, value: str, allowed: set[str]) -> str:
    normalized = value.strip().upper()
    if normalized not in allowed:
        raise ValueError(f"{label} must be one of {', '.join(sorted(allowed))}")
    return normalized


def validate_name(label: str, value: str) -> str:
    cleaned = value.strip()
    if not cleaned:
        raise ValueError(f"{label} is required")
    if len(cleaned) > 63:
        raise ValueError(f"{label} must be <= 63 characters")
    return cleaned


def validate_port(label: str, value: Any) -> int:
    try:
        port = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{label} must be an integer") from exc
    if port < 0 or port > 65535:
        raise ValueError(f"{label} must be between 0 and 65535")
    return port


def validate_ip(label: str, value: str) -> str:
    cleaned = value.strip()
    try:
        ipaddress.ip_address(cleaned)
    except ValueError as exc:
        raise ValueError(f"{label} must be an IP address, got: {cleaned}") from exc
    return cleaned


def validate_header(value: str) -> str:
    header = value.strip()
    if not header:
        raise ValueError("--xff-header is required")
    if len(header) > 63:
        raise ValueError("--xff-header must be <= 63 characters")
    return header


def node_name(host: str, port: int, index: int) -> str:
    base = SAFE_NAME_RE.sub("_", f"node_{index}_{host}_{port}").strip("_")
    return base[:63] or f"node_{index}"


def parse_node(value: str, index: int) -> dict[str, Any]:
    match = NODE_RE.match(value.strip())
    if not match:
        raise ValueError(f"--node must use address:port, got: {value}")
    host = validate_ip("--node host", match.group("host"))
    port = validate_port("--node port", match.group("port"))
    return {
        "name": node_name(host, port, index),
        "type": "ADDRESS",
        "address": host,
        "port": port,
        "state": "ENABLE",
        "weight": 10,
        "priority_level": 1,
    }


def create_http_profile_operation(name: str, header: str, description: str) -> dict[str, Any]:
    return {
        "id": "create-http-profile-xff",
        "action": "create",
        "schema": "config.http_profile",
        "document": "slb/http-profile.js",
        "payload": {
            "name": name,
            "description": description,
            "source_address": {
                "operation": "REQUEST-HEADER-INSERT-SRCIP",
                "request_header": header,
            },
        },
    }


def create_pool_operation(name: str, nodes: list[dict[str, Any]], description: str) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "name": name,
        "description": description,
        "method": "ROUND-ROBIN",
    }
    if nodes:
        payload["nodes"] = nodes
    return {
        "id": "create-pool",
        "action": "create",
        "schema": "config.pool",
        "document": "slb/pool.js",
        "payload": payload,
    }


def create_pre_rule_http_operation(args: argparse.Namespace, pool: str) -> dict[str, Any]:
    pre_rule_name = validate_name("--create-pre-rule-http", args.create_pre_rule_http)
    action = normalize_choice("--pre-rule-action", args.pre_rule_action, PRE_RULE_ACTIONS)
    payload: dict[str, Any] = {
        "name": pre_rule_name,
        "description": args.description,
        "service": "HTTP",
        "source_address": {"type": "ALL"},
        "action": action,
    }

    if action in {"SCHED-POOL", "SCHED-POOL-AND-REWRITE"}:
        payload["sched_pool"] = validate_name("--pre-rule-sched-pool", args.pre_rule_sched_pool or pool)
        payload["sched_failure"] = "NEXT-RULE"
    if args.pre_rule_uri_pattern:
        payload["http_request_uri_rule"] = {
            "mode": normalize_choice("--pre-rule-uri-mode", args.pre_rule_uri_mode, URI_MATCH_MODES),
            "case_sensitive": args.pre_rule_case_sensitive,
            "pattern": args.pre_rule_uri_pattern,
        }

    return {
        "id": "create-http-pre-rule",
        "action": "create",
        "schema": "config.pre_rule_http",
        "document": "slb/pre-rule/http.js",
        "payload": payload,
    }


def virtual_service_operation(
    args: argparse.Namespace,
    pool: str,
    http_profile: str | None,
    pre_rules: list[str],
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "name": validate_name("--vs-name", args.vs_name),
        "description": args.description,
        "state": "ENABLE",
        "service": normalize_choice("--service", args.service, SERVICE_TYPES),
        "vips": [validate_ip("--vip", item) for item in args.vip],
        "vports": [str(validate_port("--vport", item)) for item in args.vport],
        "pool": pool,
    }
    if http_profile:
        payload["http_profile"] = http_profile
    if pre_rules:
        payload["pre_rules"] = pre_rules
    return {
        "id": "create-virtual-service",
        "action": "create",
        "schema": "config.virtual_service",
        "document": "slb/virtual-service.js",
        "payload": payload,
    }


def build_bundle(args: argparse.Namespace) -> dict[str, Any]:
    pool = validate_name("--pool", args.pool)
    nodes = [parse_node(value, index) for index, value in enumerate(args.node, start=1)]
    operations: list[dict[str, Any]] = []
    recipes: list[str] = []

    http_profile = args.http_profile
    if args.create_http_profile_xff:
        http_profile = validate_name("--create-http-profile-xff", args.create_http_profile_xff)
        operations.append(create_http_profile_operation(http_profile, validate_header(args.xff_header), args.description))
        recipes.append("http-profile-xff")
    elif http_profile:
        http_profile = validate_name("--http-profile", http_profile)

    if args.create_pool or nodes:
        operations.append(create_pool_operation(pool, nodes, args.description))
        recipes.append("pool")

    pre_rules = [validate_name("--pre-rule", value) for value in args.pre_rule]
    if args.create_pre_rule_http:
        operations.append(create_pre_rule_http_operation(args, pool))
        pre_rules.append(validate_name("--create-pre-rule-http", args.create_pre_rule_http))
        recipes.append("http-pre-rule")

    operations.append(virtual_service_operation(args, pool, http_profile, pre_rules))
    return {
        "version": 1,
        "generator": "render_slb_bundle.py",
        "recipes": recipes,
        "operations": operations,
    }


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        workdir = require_workdir(args.workdir)
        out = args.out or workdir / DEFAULT_BUNDLE_NAME
        cleaned = remove_generated_artifacts(workdir, keep={out})
        bundle = build_bundle(args)
        write_json(out, bundle)
        artifacts = update_artifacts(workdir, bundle=out)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 2

    print(
        short_summary(
            ok=True,
            bundle=str(out),
            artifacts=str(artifacts),
            cleaned_count=len(cleaned),
            operation_count=len(bundle["operations"]),
            recipes=bundle["recipes"],
            workflow="slb-create-bundle",
            next_command=(
                "python3 skills/ad-config-ops/scripts/ad_ops_flow.py plan-and-render "
                f"--skill-root skills/ad-config-ops --bundle {out} --workdir {workdir}"
            ),
        ),
        end="",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
